"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.api = void 0;
const _BUILD_ID = '20260408-subbottom-v2';
console.log('[CF Boot] Build:', _BUILD_ID);
const https_1 = require("firebase-functions/v2/https");
const express_1 = __importDefault(require("express"));
const middleware_1 = require("./middleware");
const widget_1 = require("./routes/widget");
const partner_1 = require("./routes/partner");
const mockup_routes_1 = require("./routes/mockup-routes");
const designs_1 = require("./routes/designs");
const categories_1 = require("./routes/categories");
const auth_1 = require("./routes/auth");
const admin_settings_1 = require("./routes/admin-settings");
const admin_stores_1 = require("./routes/admin-stores");
const admin_products_1 = require("./routes/admin-products");
const public_1 = require("./routes/public");
const file_routes_1 = require("./routes/file-routes");
const admin_orders_1 = require("./routes/admin-orders");
const stripe_webhooks_1 = require("./routes/stripe-webhooks");
const claims_1 = require("./routes/claims");
const products_page_1 = require("./routes/products-page");
const brain_1 = require("./routes/brain");
const members_1 = require("./routes/members");
const public_stores_1 = require("./routes/public-stores");
const dynamics_1 = require("./routes/dynamics");
const referral_1 = require("./routes/referral");
const checkout_1 = require("./routes/checkout");
const catalog_1 = require("./routes/catalog");
const tiers_1 = require("./routes/tiers");
const admin_misc_1 = require("./routes/admin-misc");
const gifts_1 = require("./routes/gifts");
const orchestration_1 = require("./routes/orchestration");
const packets_1 = require("./routes/packets");
const images_1 = require("./routes/images");
const member_files_1 = require("./routes/member-files");
const store_files_1 = require("./routes/store-files");
const seo_1 = require("./routes/seo");
const marketplace_1 = require("./routes/marketplace");
const external_sites_1 = require("./routes/external-sites");
const core_routes_1 = require("./routes/core-routes");
const app = (0, express_1.default)();
app.use(middleware_1.corsMiddleware);
app.use(express_1.default.json({ limit: '50mb' }));
app.use(express_1.default.urlencoded({ extended: false }));
app.use(middleware_1.apiPrefixMiddleware);
(0, widget_1.register)(app);
(0, partner_1.register)(app);
(0, mockup_routes_1.register)(app);
(0, designs_1.register)(app);
(0, categories_1.register)(app);
(0, auth_1.register)(app);
(0, admin_settings_1.register)(app);
(0, admin_stores_1.register)(app);
(0, admin_products_1.register)(app);
(0, public_1.register)(app);
(0, file_routes_1.register)(app);
(0, admin_orders_1.register)(app);
(0, stripe_webhooks_1.register)(app);
(0, claims_1.register)(app);
(0, products_page_1.register)(app);
(0, brain_1.register)(app);
(0, members_1.register)(app);
(0, public_stores_1.register)(app);
(0, dynamics_1.register)(app);
(0, referral_1.register)(app);
(0, checkout_1.register)(app);
(0, catalog_1.register)(app);
(0, tiers_1.register)(app);
(0, admin_misc_1.register)(app);
(0, gifts_1.register)(app);
(0, orchestration_1.register)(app);
(0, packets_1.register)(app);
(0, images_1.register)(app);
(0, member_files_1.register)(app);
(0, store_files_1.register)(app);
(0, seo_1.register)(app);
(0, marketplace_1.register)(app);
(0, external_sites_1.register)(app);
(0, core_routes_1.register)(app);
app.use((err, _req, res, _next) => {
    console.error('Unhandled error:', err);
    res.status(500).json({ error: 'Internal server error' });
});
exports.api = (0, https_1.onRequest)({
    timeoutSeconds: 540,
    memory: '1GiB',
    cors: true,
}, app);
//# sourceMappingURL=index.js.map