import { expect, it, vi } from 'vitest';
import express from 'express';
import request from 'supertest';
const m = vi.hoisted(() => ({ rows: {} as Record<string, any> }));
vi.mock('../../core', () => ({ db: { collection: (c: string) => ({ doc: (id: string) => ({ get: async () => ({ exists: !!m.rows[c]?.[id], data: () => m.rows[c]?.[id] }) }) }) } }));
vi.mock('../../middleware', () => ({}));
vi.mock('../../services/printful', () => ({}));
vi.mock('../../services/printify', () => ({}));
vi.mock('../../services/storage-helpers', () => ({}));
vi.mock('../../services/pricing', () => ({ getSizeUpcharges: async () => ({}) }));
vi.mock('../../services/mockup-generator', () => ({}));
vi.mock('../../services/email', () => ({}));
vi.mock('../../services/composite-image', () => ({}));
import { register } from '../../routes/store-files';
const app = express(); register(app);
it.each(['https://www.youtube.com/watch?v=DVUbzOk8mCc', 'https://storage.example/graphic.mp4'])('returns the linked packet video without substituting the static snapshot: %s', async (source) => {
  m.rows = { admin_catalog_instances: { shirt: { currentPacketId: 'packet', resolved: { title: 'Monument', description: 'A Bella + Canvas 3001 tee in Forest.', pricing: { customerPrice: 24.61 } } } }, productPackets: { packet: { qrProductState: 'qr_play', playMediaUrl: source, landingPageSnapshotUrl: 'static.png', qrOnlyUrl: 'qr.png' } } };
  const res = await request(app).get('/store/product/shirt');
  expect(res.status).toBe(200);
  expect(res.body).toMatchObject({ qrProductType: 'qr-play', playMediaUrl: source, qrCodeUrl: 'qr.png', price: 24.61 });
  expect(res.body.description).toBe('A QR Gear tee in Forest.');
  expect(m.rows.admin_catalog_instances.shirt.resolved.description).toContain('Bella + Canvas 3001');
});
